// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://bcwvsmxdakkhjdqlpnso.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJjd3ZzbXhkYWtraGpkcWxwbnNvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTgyNjkzMDAsImV4cCI6MjA3Mzg0NTMwMH0.vou829SZZXG_E1FPvZt9DvieLKZUELSLIcdcNCp2a0g";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});